// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC97qvv4lgw3spN46ItRPChc29NL5Sphik',
    appId: '1:430745263684:web:c91e8ee479967ae51de611',
    messagingSenderId: '430745263684',
    projectId: 'diariodeviagens-62425',
    authDomain: 'diariodeviagens-62425.firebaseapp.com',
    storageBucket: 'diariodeviagens-62425.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9KlbRwz7VyxGN3-vL12nTuRmnonp2Mvw',
    appId: '1:430745263684:android:d718de1a7b51c3f51de611',
    messagingSenderId: '430745263684',
    projectId: 'diariodeviagens-62425',
    storageBucket: 'diariodeviagens-62425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0cSzfglRRvs97e2KzDUqS1sXF6wCkqqg',
    appId: '1:430745263684:ios:1d70281d3e9820f41de611',
    messagingSenderId: '430745263684',
    projectId: 'diariodeviagens-62425',
    storageBucket: 'diariodeviagens-62425.appspot.com',
    iosBundleId: 'com.example.diariodeviagens',
  );
}
